packages:
  - 'crates/napi'
  - 'packages/*'
  - 'npm/@nemcss/*'
  - 'editors/*'

allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
