use std::fs;
use std::path::PathBuf;
use std::{collections::HashMap, path::Path};

use miette::Diagnostic;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::tokens::{
    ResolveTokensError, ResolvedToken, resolve_all_semantic_groups, resolve_all_tokens,
};
use crate::{ResolveSemanticError, ResolvedSemanticGroup};

/// The name of the NemCSS configuration file.
pub const CONFIG_FILE_NAME: &str = "nemcss.config.json";

/// Custom deserializer for non-empty prefixes.
/// It deserializes a string and returns an error if the string is empty.
fn deserialize_non_empty_prefix<'de, D: serde::Deserializer<'de>>(
    d: D,
) -> Result<String, D::Error> {
    let s = String::deserialize(d)?;
    if s.is_empty() {
        return Err(serde::de::Error::custom("prefix must not be empty"));
    }
    Ok(s)
}

/// Custom deserializer for non-empty properties.
/// It deserializes a string and returns an error if the string is empty.
fn deserialize_non_empty_property<'de, D: serde::Deserializer<'de>>(
    d: D,
) -> Result<String, D::Error> {
    let s = String::deserialize(d)?;
    if s.is_empty() {
        return Err(serde::de::Error::custom("property must not be empty"));
    }
    Ok(s)
}

/// NemCssConfig represents the configuration of the NemCSS util.
/// It contains the paths to the content files and the design tokens, as well as the theme configuration.
#[derive(Debug, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct NemCssConfig {
    /// JSON schema URL present in files generated by `nemcss init`
    #[serde(rename = "$schema", default, skip_serializing_if = "Option::is_none")]
    #[schemars(skip)]
    pub schema_url: Option<String>,

    /// Vector of glob patterns to determine which content files to target.
    /// Content files will be used to determine which CSS classes to generate.
    pub content: Vec<String>,

    /// Path to directory containing the design tokens.
    #[serde(rename = "tokensDir", default = "get_default_tokens_dir")]
    pub tokens_dir: PathBuf,

    /// Theme configuration.
    pub theme: Option<ThemeConfig>,

    /// Semantic tokens
    pub semantic: Option<SemanticConfig>,

    /// The base directory of the NemCSS project.
    #[serde(skip)]
    pub base_dir: PathBuf,
}

/// Returns the default value for the tokensDir field.
fn get_default_tokens_dir() -> PathBuf {
    PathBuf::from("design-tokens")
}

/// NemCssConfigError represents the error type when loading the NemCSS configuration.
#[derive(Debug, Error, Diagnostic)]
pub enum NemCssConfigError {
    #[error("failed to read NemCSS config file: {0}")]
    #[diagnostic(code(nemcss::config::read_config_file))]
    ReadConfigFile(std::io::Error),

    #[error("failed to parse NemCSS config file: {0}")]
    #[diagnostic(code(nemcss::config::parse_config_file))]
    ParseConfigFile(serde_json::Error),
}

impl NemCssConfig {
    /// Creates a new NemCssConfig instance from a given path.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use config::NemCssConfig;
    /// use std::path::Path;
    ///
    /// let config = NemCssConfig::from_path("nemcss.config.json")?;
    /// println!("Tokens directory: {:?}", config.tokens_dir);
    /// # Ok::<(), Box<dyn std::error::Error>>(())
    /// ```
    pub fn from_path<T: AsRef<Path>>(path: T) -> Result<Self, NemCssConfigError> {
        let config_path = path.as_ref();

        let content = fs::read_to_string(config_path).map_err(NemCssConfigError::ReadConfigFile)?;

        let mut config: NemCssConfig =
            serde_json::from_str(&content).map_err(NemCssConfigError::ParseConfigFile)?;

        let base_dir = config_path
            .parent()
            .map(|p| p.to_path_buf())
            .unwrap_or_default();
        config.base_dir = base_dir;

        Ok(config)
    }

    /// Resolves all design tokens based on the configuration.
    ///
    /// It scans the tokens directory and loads the design tokens from the files.
    /// It then generates the utilities for each token based on the configuration.
    /// Finally, it returns a map of resolved tokens.
    ///
    /// # Returns
    ///
    /// A map of resolved tokens, where the key is the name of the token and the value is the resolved token (containing the token values, prefix, and utilities).
    ///
    /// # Errors
    /// This function returns an error if the tokens directory is not found or if the design tokens
    /// cannot be loaded.
    pub fn resolve_all_tokens(&self) -> Result<HashMap<String, ResolvedToken>, ResolveTokensError> {
        resolve_all_tokens(self)
    }

    pub fn resolve_semantic_groups(
        &self,
        primitive_tokens: &HashMap<String, ResolvedToken>,
    ) -> Result<HashMap<String, ResolvedSemanticGroup>, ResolveSemanticError> {
        resolve_all_semantic_groups(self.semantic.as_ref(), primitive_tokens)
    }

    /// Get absolute path to the tokens directory.
    pub fn tokens_dir(&self) -> PathBuf {
        self.base_dir.join(&self.tokens_dir)
    }

    /// Get a glob set of the content paths.
    pub fn content_glob_set(&self) -> Result<globset::GlobSet, globset::Error> {
        let mut builder = globset::GlobSetBuilder::new();
        for pattern in &self.content {
            builder.add(globset::Glob::new(pattern)?);
        }
        builder.build()
    }
}

/// ThemeConfig represents the configuration of the theme.
/// It contains the design tokens configuration per token type.
#[derive(Debug, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct ThemeConfig {
    /// The design tokens configuration.
    /// This is a map of the design tokens to their configuration.
    /// The key is the name of the design token. The value is the configuration of the design token.
    #[serde(flatten)]
    pub tokens: HashMap<String, TokenConfig>,
}

/// TokenConfig represents the configuration of a single design token.
/// You can override the default configuration by specifying the source, prefix, and utilities.
///
/// # Examples
///
/// In your `nemcss.config.json`:
///
/// ```json
/// {
///   "theme": {
///      "colors": {
///        "source": "design-tokens/colors.json",
///        "prefix": "color",
///        "utilities": [
///           {
///             "prefix": "highlight",
///             "property": "background-color"
///           }
///        ]
///      }
///
///   }
/// }
/// ```
///
/// With a token variant "primary" in colors.json, this generates:
/// - CSS custom property: `--color-primary`
/// - Utility class: `.highlight-primary { background-color: var(--color-primary); }`
#[derive(Debug, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct TokenConfig {
    /// Path to the tokens file.
    /// It will make it possible to override the default configuration for a given token.
    pub source: PathBuf,

    /// The token prefix is used to generate the custom properties for the given token.
    /// For example, if prefix is "color", the token prefix will be "color-".
    /// If the color tokens include a "primary" variant, the custom property generated will be
    /// "--color-primary".
    pub prefix: Option<String>,

    /// Utilities are used to generate utility classes for the given token.
    pub utilities: Option<Vec<TokenUtilityConfig>>,
}

/// TokenUtilityConfig represents the configuration of a utility class for a given token.
#[derive(Debug, Default, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct TokenUtilityConfig {
    /// The prefix that will be used to generate the utility class.
    /// For example, if the prefix is "bg", the utility class will be "bg-[TOKEN VARIANT]".
    #[serde(deserialize_with = "deserialize_non_empty_prefix")]
    #[schemars(extend("minLength"=1))]
    pub prefix: String,
    /// The CSS property that will use the design token value.
    #[serde(deserialize_with = "deserialize_non_empty_property")]
    #[schemars(extend("minLength"=1))]
    pub property: String,
}

/// The semantic config enables the creation of groups of semantic tokens (e.g. for "text",
/// "background") with their own configuration (e.g. the CSS property they target and the tokens
/// they use)
#[derive(Debug, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct SemanticConfig {
    /// Groups of semantic tokens
    #[serde(flatten)]
    pub groups: HashMap<String, SemanticGroupConfig>,
}

/// A single semantic token config
#[derive(Debug, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct SemanticGroupConfig {
    /// CSS property this group targets (e.g. "color", "background-color")
    #[serde(deserialize_with = "deserialize_non_empty_property")]
    #[schemars(extend("minLength"=1))]
    pub property: String,
    /// Mapping between a semantic name and an existing design token value
    /// e.g. "primary" -> "{colors.blue-800}"
    pub tokens: HashMap<String, String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_content_glob_matches_correct_files() {
        let config = NemCssConfig {
            content: vec!["content/**/*.md".to_string(), "src/**/*.svelte".to_string()],
            ..Default::default()
        };

        let glob_set = config.content_glob_set().unwrap();

        // Matches the correct files in `content`
        assert!(glob_set.is_match("content/foo.md"));
        assert!(glob_set.is_match("content/bar/baz.md"));
        assert!(!glob_set.is_match("content/foo.txt"));

        // Matches the correct files in `src`
        assert!(glob_set.is_match("src/App.svelte"));
        assert!(glob_set.is_match("src/components/Button.svelte"));
        assert!(!glob_set.is_match("src/components/Error.tsx"));
    }

    #[test]
    fn test_content_glob_set_invalid_pattern() {
        let config = NemCssConfig {
            content: vec!["[invalid/**/*.md".to_string()],
            ..Default::default()
        };

        let glob_set = config.content_glob_set();

        assert!(glob_set.is_err());
    }

    mod schema_robustness {
        use super::*;

        #[test]
        fn valid_config_round_trips() {
            let json = r#"
            {
            "content": ["src/**/*.svelte"],
            "tokensDir": "custom-tokens"
            }
            "#;

            assert!(serde_json::from_str::<NemCssConfig>(json).is_ok());
        }

        #[test]
        fn schema_field_is_accepted() {
            let json = r#"
            {
            "$schema": "./nemcss.schema.json",
            "content": ["src/**/*.svelte"],
            "tokensDir": "custom-tokens"
            }
            "#;
            assert!(
                serde_json::from_str::<NemCssConfig>(json).is_ok(),
                "$schema field should be accepted in the config"
            );
        }

        #[test]
        fn unknown_top_level_field_is_rejected() {
            let json = r#"
            {
                "cotent": ["src/**/*.svelte"]
            }
            "#;
            assert!(
                serde_json::from_str::<NemCssConfig>(json).is_err(),
                "typo in top-level fields should be a parse error"
            );
        }
    }

    mod deserialize_non_empty_string {
        use super::*;

        #[test]
        fn test_deserialize_fails_on_empty_utility_prefix() {
            let json = r#"
            {
                "content": [],
                "theme": {
                    "colors": {
                        "source": "design-tokens/colors.json",
                        "utilities": [
                            { "prefix": "", "property": "background-color" }
                        ]
                    }
                }
            }
                "#;
            assert!(serde_json::from_str::<NemCssConfig>(json).is_err());
        }

        #[test]
        fn test_deserialize_fails_on_empty_semantic_property() {
            let json = r#"
            {
                "content": [],
                "theme": {
                    "colors": {
                        "source": "design-tokens/colors.json"
                    }
                },
                "semantic": {
                    "text": {
                        "property": "",
                        "tokens": {
                            "primary": "{colors.blue-500}"
                        }
                    }
                }
            }"#;
            assert!(serde_json::from_str::<NemCssConfig>(json).is_err());
        }
    }

    mod semantic_tokens {
        use super::*;

        #[test]
        fn test_deserialize_config_with_semantic_tokens() {
            let json = r#"{
                "content": [],
                "semantic": {
                    "text": {
                        "property": "color",
                        "tokens": {
                            "primary": "{colors.blue-500}",
                            "error": "{colors.red-700}"
                        }
                    }
                }
            }"#;

            let config: NemCssConfig = serde_json::from_str(json).unwrap();
            let semantic = config.semantic.unwrap();
            let text = semantic.groups.get("text").unwrap();
            assert_eq!(text.property, "color");
            assert_eq!(text.tokens.get("primary").unwrap(), "{colors.blue-500}");
        }

        #[test]
        fn test_config_without_semantic_is_valid() {
            let json = r#"{ "content": [] }"#;
            let config: NemCssConfig = serde_json::from_str(json).unwrap();
            assert!(config.semantic.is_none());
        }
    }
}
