/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Extracts the classes from a given content.
 * It is a wrapper around the `extractor` module.
 * Normally, `extractor::extract_classes` returns a HashSet.
 * For compatibility with the Node API, we convert it to a Vec.
 */
export declare function extractClasses(content: string): Array<string>

/**
 * Generates the CSS from a given configuration file and outputs the CSS that will be used
 * to replace the `@nemcss base;` and `@nemcss utilities;` directives.
 */
export declare function generateCss(configPath: string, usedClasses?: Array<string> | undefined | null): GeneratedCss

export interface GeneratedCss {
  baseCss: string
  utilitiesCss: string
}

/**
 * JsResolvedToken is the configuration of a resolved token.
 * It is used to generate both the CSS custom properties and the utilities for a given design token.
 *
 * # Example
 * ```no_run
 * {
 *     prefix: "bg",
 *     tokens: [
 *         { name: "color", value: ["red"] },
 *         { name: "opacity", value: ["0.5"] }
 *     ],
 *     utilities: [
 *         { prefix: "bg", property: "background-color" },
 *         { prefix: "bg", property: "background-image" }
 *     ]
 * }
 * ```
 */
export interface JsResolvedToken {
  prefix: string
  tokens: Array<JsTokenEntry>
  utilities: Array<JsTokenUtility>
}

/**
 * JsTokenEntry is the configuration of a token entry.
 * In Rust, we have an enum (Simple or List). We simplify it to an array of strings.
 */
export interface JsTokenEntry {
  /** The name of the token entry. */
  name: string
  /** The value of the token entry. */
  value: Array<string>
}

/**
 * JsTokenUtility is the configuration of a utility class for a given token.
 *
 * # Example
 * ```no_run
 * { prefix: "bg", property: "background-color" }
 * ```
 */
export interface JsTokenUtility {
  prefix: string
  property: string
}
